-- =============================================================================
-- Migration 119: task_comments — thread per task (events + free comments)
-- =============================================================================
-- Each task gets a chronological thread mixing two kinds of rows:
--   event_type = 'comment'               → free text typed by a team member
--   event_type = <action>                → system event generated by a task
--                                          action (created, assigned, reassigned,
--                                          status_changed, completed, reopened,
--                                          snoozed)
--
-- author_id is always the user who caused the row (never NULL). For system
-- events that is the person who performed the action; for comments that is the
-- person who typed it.
--
-- RLS:
--   SELECT  — any authenticated user (task visibility is enforced at the app layer)
--   INSERT  — authenticated; author_id must equal auth.uid()
--   UPDATE  — author can edit their own comment body (event rows are immutable in
--              the UI, but the DB doesn't need a separate CHECK — the app simply
--              never renders an edit control for non-comment rows)
--   DELETE  — no hard-delete policy; admins use soft-delete (set deleted_at)
--             via a SECURITY DEFINER RPC (added below)
-- =============================================================================

CREATE TABLE public.task_comments (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id     uuid        NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
  author_id   uuid        NOT NULL REFERENCES auth.users(id)  ON DELETE CASCADE,
  body        text        NOT NULL CHECK (char_length(body) BETWEEN 1 AND 4000),
  event_type  text        NOT NULL DEFAULT 'comment'
                          CHECK (event_type IN (
                            'comment',
                            'created',
                            'assigned',
                            'reassigned',
                            'status_changed',
                            'completed',
                            'reopened',
                            'snoozed'
                          )),
  metadata    jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  edited_at   timestamptz,
  deleted_at  timestamptz
);

-- Fast lookup of all thread rows for a given task, newest-last.
CREATE INDEX idx_task_comments_task ON public.task_comments (task_id, created_at);

ALTER TABLE public.task_comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "task_comments_select" ON public.task_comments
  FOR SELECT TO authenticated
  USING (deleted_at IS NULL);

CREATE POLICY "task_comments_insert" ON public.task_comments
  FOR INSERT TO authenticated
  WITH CHECK (author_id = auth.uid());

-- Authors may update the body of their own *comment* rows. Event rows are
-- never updated in practice (the app shows no edit UI for them), but the
-- policy is the same — only the owner can touch their row.
CREATE POLICY "task_comments_update" ON public.task_comments
  FOR UPDATE TO authenticated
  USING  (author_id = auth.uid())
  WITH CHECK (author_id = auth.uid());

-- Soft-delete RPC for admins. Hard-delete is not exposed.
CREATE OR REPLACE FUNCTION public.soft_delete_task_comment(p_comment_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin boolean;
BEGIN
  SELECT is_admin INTO v_is_admin FROM public.profiles WHERE id = auth.uid();
  IF NOT coalesce(v_is_admin, false) THEN
    RAISE EXCEPTION 'unauthorized';
  END IF;
  UPDATE public.task_comments
    SET deleted_at = now()
    WHERE id = p_comment_id AND deleted_at IS NULL;
END;
$$;

GRANT EXECUTE ON FUNCTION public.soft_delete_task_comment(uuid) TO authenticated;
